### PR TITLE
fix: ghibli example

### PR DESCRIPTION
**Pull request by mezotv**
This makes the ghibli example work again with a new API with a updated and improved dataset!

### CODE REVIEW

**Comment by taniarascia** [comment]
Thanks!

**Comment by mezotv** [comment]
> Thanks!

I hope this isn't to much to ask for but would it be possible to edit [the blog post](https://www.taniarascia.com/how-to-connect-to-an-api-with-javascript/) since the new API makes it work again?

**Comment by taniarascia** [comment]
Hi @mezotv, sorry I've been meaning to get to this but haven't sat down with the website for quite a while. I will try to get to it soon!

**Comment by mezotv** [comment]
> Hi @mezotv, sorry I've been meaning to get to this but haven't sat down with the website for quite a while. I will try to get to it soon!

That would be awesome thanks!

**Pull request merged**
